## for industry names

#' @export

IndustryNames <- c("Accommodation.and.Food.Services"="Hospitality",
                   "Accommodation.and.food.services"="Hospitality",
                   "Accommodation.and.food.services.H"="Hospitality",
                   "H.Accommodation.and.Food.Services"="Hospitality",
                   "Accommodation.Cafes.and.Restaurants"="Hospitality",
                   "Administrative.and.Support.Services"="Administration",
                   "Administrative.and.support.services"="Administration",
                   "Administrative.and.support.services.N"="Administration",
                   "N.Administrative.and.Support.Services"="Administration",
                   "Agriculture.Forestry.and.Fishing"="Agriculture",
                   "Agriculture.forestry.and.fishing"="Agriculture",
                   "Agriculture.forestry.and.fishing.A"="Agriculture",
                   "A.Agriculture.Forestry.and.Fishing"="Agriculture",
                   "A.Agriculture.forestry.and.fishing"="Agriculture",
                   "Arts.and.Recreation.Services"="ArtsRecreation",
                   "Arts.and.recreation.services"="ArtsRecreation",
                   "Arts.and.recreation.services.R"="ArtsRecreation",
                   "R.Arts.and.Recreation.Services"="ArtsRecreation",
                   "Cultural.and.Recreational.Services"="ArtsRecreation",
                   "Construction"="Construction",
                   "Construction.E"="Construction",
                   "E.Construction"="Construction",
                   "Education.and.Training"="Education",
                   "Education.and.training"="Education",
                   "Education.and.training.P"="Education",
                   "P.Education.and.Training"="Education",
                   "Education"="Education",
                   "Electricity.Gas.Water.and.Waste.Services"="Utilities",
                   "Electricity.gas.water.and.waste.services"="Utilities",
                   "Electricity.gas.water.and.waste.services.D"="Utilities",
                   "D.Electricity.Gas.Water.and.Waste.Services"="Utilities",
                   "Electricity.Gas.and.Water.Supply" = "Utilities",
                   "Financial.and.Insurance.Services"="FinanceInsurance",
                   "Financial.and.insurance.services"="FinanceInsurance",
                   "Financial.and.insurance.services.K"="FinanceInsurance",
                   "K.Financial.and.Insurance.Services"="FinanceInsurance",
                   "Health.Care.and.Social.Assistance"="HealthSocial",
                   "Health.care.and.social.assistance"="HealthSocial",
                   "Health.care.and.social.assistance.Q"="HealthSocial",
                   "Health.and.Community.Services"="HealthSocial",
                   "Q.Health.Care.and.Social.Assistance"="HealthSocial",
                   "Information.Media.and.Telecommunications"="Media",
                   "Information.media.and.telecommunications"="Media",
                   "Information.media.and.telecommunic.ations"="Media",
                   "Information.media.and.telecommunications.J"="Media",
                   "J.Information.Media.and.Telecommunications"="Media",
                   "Communication.Services"="Media",
                   "Manufacturing"="Manufacturing",
                   "Manufacturing.C"="Manufacturing",
                   "C.Manufacturing"="Manufacturing",
                   "Mining"="Mining",
                   "Mining.B"="Mining",
                   "B.Mining"="Mining",
                   "Other.Services"="OtherServices",
                   "Other.services"="OtherServices",
                   "Other.services.S"="OtherServices",
                   "S.Other.Services"="OtherServices",
                   "Personal.and.Other.Services"="OtherServices",
                   "Professional.Scientific.and.Technical.Services"="ProfScientificTech",
                   "Professional.scientific.and.technical.services"="ProfScientificTech",
                   "Professional.scientific.and.technical.services.M"="ProfScientificTech",
                   "M.Professional.Scientific.and.Technical.Services"="ProfScientificTech",
                   "Public.Administration.and.Safety"="PublicAdminSafety",
                   "Public.administration.and.safety"="PublicAdminSafety",
                   "Public.administration.and.safety.O"="PublicAdminSafety",
                   "O.Public.Administration.and.Safety"="PublicAdminSafety",
                   "Rental.Hiring.and.Real.Estate.Services"="RentalRealEstate",
                   "Rental.hiring.and.real.estate.services"="RentalRealEstate",
                   "Rental.hiring.and.real.estate.services.L"="RentalRealEstate",
                   "L.Rental.Hiring.and.Real.Estate.Services"="RentalRealEstate",
                   "Property.and.Business.Services"="PropertyBusinessServices",
                   "Retail.Trade"="Retail",
                   "Retail.trade"="Retail",
                   "Retail.trade.G"="Retail",
                   "G.Retail.Trade"="Retail",
                   "Transport.Postal.and.Warehousing" ="TransportWarehousing",
                   "Transport.postal.and.warehousing" ="TransportWarehousing",
                   "Transport.postal.and.warehousing.I" ="TransportWarehousing",
                   "I.Transport.Postal.and.Warehousing" ="TransportWarehousing",
                   "Transport.and.Storage"="TransportWarehousing",
                   "Wholesale.Trade"="Wholesale",
                   "Wholesale.trade"="Wholesale",
                   "Wholesale.trade.F"="Wholesale",
                   "F.Wholesale.Trade"="Wholesale",
                   "Other.Selected.Industries"="OtherSelectedIndustries",
                   "Total"="Total",
                   "Selected.Industries.Excluding.Agriculture.Forestry.and.Fishing"="SelectedIndustriesExlAg",
                   "12.Selected.industries.a"="12SelectedIndustries",
                   "12.Selected.industries.(a)"="12SelectedIndustries",
                   "12.Selected.industries.b"="12SelectedIndustries",
                   "12.Selected.industries.(b)"="12SelectedIndustries",
                   "12.Selected.industries.c"="12SelectedIndustries",
                   "16MarketSectorIndustries"="16MarketSectorIndustries",
                   "16.Market.Sector.industries.b"="16MarketSectorIndustries",
                   "16.Market.Sector.industries.(b)"="16MarketSectorIndustries",
                   "16.Market.Sector.industries.c"="16MarketSectorIndustries",
                   "16.Market.Sector.industries.(c)"="16MarketSectorIndustries",
                   "16.Market.Sector.industries.d"="16MarketSectorIndustries",
                   "Total.Industry"="16MarketSectorIndustries",
                   "All.Industries"="AllIndustries",
                   "ALL.INDUSTRIES" = "AllIndustries",
                   "All.industries"="AllIndustries",
                   "Total.all.industries" = "AllIndustries",
                   "1"="Agriculture",
                   "2"="Mining",
                   "3"="Manufacturing",
                   "4"="Utilities",
                   "5"="Construction",
                   "6"="Wholesale",
                   "7"="Retail",
                   "8"="Hospitality",
                   "9"="TransportWarehousing",
                   "10"="Media",
                   "11"="FinanceInsurance",
                   "12"="RentalRealEstate",
                   "13"="ProfScientificTech",
                   "14"="Administration",
                   "15"="PublicAdminSafety",
                   "16"="Education",
                   "17"="HealthSocial",
                   "18"="ArtsRecreation",
                   "19"="OtherServices",
                   "Ownership.of.dwellings" = "Ownership.of.dwellings",
                   "Ownership.transfer.costs"="Ownership.transfer.costs")
#' @export

MarketSector16Industries <- c("Agriculture",
                              "Mining",
                              "Manufacturing",
                              "Utilities",
                              "Construction",
                              "Wholesale",
                              "Retail",
                              "Hospitality",
                              "TransportWarehousing",
                              "Media",
                              "FinanceInsurance",
                              "RentalRealEstate",
                              "ProfScientificTech",
                              "Administration",
                              "ArtsRecreation",
                              "OtherServices",
                              "16MarketSectorIndustries")
#' @export

Selected12Industries <- c("Agriculture",
                          "Mining",
                          "Manufacturing",
                          "Utilities",
                          "Construction",
                          "Wholesale",
                          "Retail",
                          "Hospitality",
                          "TransportWarehousing",
                          "Media",
                          "FinanceInsurance" ,
                          "ArtsRecreation",
                          "12SelectedIndustries")
#' @export

WageDataAvailIndustries <- c("Mining",
                       "Manufacturing",
                       "Utilities",
                       "Construction",
                       "Wholesale",
                       "Retail",
                       "Hospitality",
                       "TransportWarehousing",
                       "Media",
                       "FinanceInsurance",
                       "RentalRealEstate",
                       "ProfScientificTech",
                       "Administration",
                       "PublicAdminSafety",
                       "Education",
                       "HealthSocial",
                       "ArtsRecreation",
                       "OtherServices",
                       "AllIndustries")

#' @export


IndustryFullNames <- c("Agriculture" = "Agriculture, forestry and fishing",
                       "Mining" = "Mining",
                       "Manufacturing" = "Manufacturing",
                       "Utilities" = "Electricity, gas, water and waste services",
                       "Construction" = "Construction",
                       "Wholesale" = "Wholesale trade",
                       "Retail" = "Retail trade" ,
                       "Hospitality" = "Accommodation and food services",
                       "TransportWarehousing" = "Transport, postal and warehousing",
                       "Media" = "Information, media and telecommunications",
                       "PropertyBusinessServices" = "Property and business services",
                       "FinanceInsurance" = "Finance and insurance services",
                       "RentalRealEstate" = "Property, hiring and real estate services",
                       "ProfScientificTech" = "Professional, scientific and technical services",
                       "Administration" = "Administrative and support services",
                       "ArtsRecreation" = "Arts and recreational services",
                       "OtherServices" = "Other services",
                       "PublicAdminSafety" = "Public administration and safety",
                       "Education" = "Education and training",
                       "HealthSocial" = "Health care and social assistance",
                       "SelectedIndustriesExlAg"="Selected Industries Excluding Agriculture",
                       "12SelectedIndustries" = "12 selected industries",
                       "16MarketSectorIndustries" =  "16 market sector industries",
                       "AllIndustries" = "All Industries")


#' @export

IndustrySectors <- c("Agriculture"="Primary/Secondary",
                    "Mining"="Primary/Secondary",
                    "Manufacturing"="Primary/Secondary",
                    "Construction"="Primary/Secondary",
                    "Wholesale"="Primary/Secondary",
                    "Retail"="Consumer Services",
                    "Hospitality"="Consumer Services",
                    "ArtsRecreation"="Consumer Services",
                    "Media"="Consumer Services",
                    "OtherServices"="Consumer Services",
                    "FinanceInsurance" ="Business Services",
                    "RentalRealEstate" ="Business Services",
                    "ProfScientificTech" ="Business Services",
                    "Administration" ="Business Services",
                    "TransportWarehousing"="Business Services",
                    "PropertyBusinessServices"="Business Services",
                    "Utilities"="Government Dominated",
                    "PublicAdminSafety"="Government Dominated",
                    "Education"="Government Dominated",
                    "HealthSocial"="Government Dominated",
                    "Total"="Aggregates",
                    "SelectedIndustriesExlAg"="Aggregates",
                    "12SelectedIndustries"="Aggregates",
                    "16MarketSectorIndustries"="Aggregates",
                    "AllIndustries"="Aggregates")
