
#' Initiate New Project Folders
#'
#' @description This function creates the standard set of project folders that are needed in each project.
#'
#' @name proj_primer
#' @param Directory This is the user directory that has already been generated by the paths package.
#' @return Creates a new set of directories in the new project directory with included YSIcss.css and YSI.png files.
#' @export
#'

proj_primer <- function(Directory = UserDir) {

  lsp_files <- paste(Directory, "Documents/packages/lsp/Report Template/", sep = "/")

  project_path <- getwd()
  print(project_path)

  #Create the subdirectory for the css folder
  projpath_css <- paste(project_path, "css", sep = "/")
  dir.create(projpath_css)

  #Copy the YSIcss.css file from the lsp project to the css directory
  file.copy(from = paste(lsp_files, "YSIcss.css", sep = "/"), to = projpath_css, overwrite = FALSE)

  #Create the subdirectory for the data folder
  projpath_data <- paste(project_path, "data", sep = "/")
  dir.create(projpath_data)

  #Create the subdirectory for the extdata folder
  projpath_extdata <- paste(project_path, "extdata", sep = "/")
  dir.create(projpath_extdata)

  #Create the subdirectory for the imgs folder
  projpath_imgs <- paste(project_path, "imgs", sep = "/")
  dir.create(projpath_imgs)

  #Create the subdirectory for the figures folder
  projpath_figures <- paste(project_path, "figures", sep = "/")
  dir.create(projpath_figures)

  #Copy the YSI.png file from the lsp project to the imgs directory
  file.copy(from = paste(lsp_files, "YSI.png", sep = "/"), to = projpath_imgs, overwrite = FALSE)

  #Create the subdirectory for the literature folder
  projpath_literature <- paste(project_path, "literature", sep = "/")
  dir.create(projpath_literature)

}
